version: '3'

tasks:
  test:
    cmds:
      # The idiomatic way to disable test caching explicitly is to use -count=1
      - go test ./pkg/... -count=1 -v --failfast

  lint:
    cmds:
      - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.12.2
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...
