name: ci
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Test
      run: go test ./pkg/... -count=1 -v --failfast

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        args: --config=./.golangci.yml --verbose
